# Generated by Django 4.2.15 on 2024-08-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
