# Generated by Django 5.0.4 on 2024-09-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_funcionario_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itenssolicitacao',
            name='classe_requisicao',
        ),
        migrations.AddField(
            model_name='itenssolicitacao',
            name='classe_requisicao',
            field=models.ManyToManyField(to='cadastro.classerequisicao'),
        ),
    ]
