# Generated by Django 4.2.15 on 2024-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_classerequisicao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cc',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cc',
            field=models.ManyToManyField(related_name='funcionario_cc', to='cadastro.cc'),
        ),
    ]
