# Generated by Django 5.0.6 on 2024-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_itenstransferencia_unidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenssolicitacao',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='itenstransferencia',
            name='nome',
            field=models.CharField(max_length=120),
        ),
    ]
