# Generated by Django 4.2.15 on 2024-08-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_operador'),
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaorequisicao',
            name='entregue',
        ),
        migrations.RemoveField(
            model_name='solicitacaotransferencia',
            name='entregue',
        ),
        migrations.AddField(
            model_name='solicitacaorequisicao',
            name='entregue_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_operador', to='cadastro.operador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaotransferencia',
            name='entregue_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_operador', to='cadastro.operador'),
            preserve_default=False,
        ),
    ]
