# Generated by Django 4.2.15 on 2024-08-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_operador'),
        ('solicitacao', '0002_remove_solicitacaorequisicao_entregue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaorequisicao',
            name='entregue_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_operador', to='cadastro.operador'),
        ),
        migrations.AlterField(
            model_name='solicitacaotransferencia',
            name='entregue_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_operador', to='cadastro.operador'),
        ),
    ]
