# Generated by Django 4.2.15 on 2024-08-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_operador_status'),
        ('solicitacao', '0006_solicitacaocadastroitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoNovaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cadastro_cc', to='cadastro.cc')),
            ],
        ),
    ]
