# Generated by Django 5.0.4 on 2024-09-16 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_classerequisicao_and_more'),
        ('solicitacao', '0007_solicitacaonovamatricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaorequisicao',
            name='classe_requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_classe', to='cadastro.classerequisicao'),
        ),
    ]
