# Generated by Django 4.2.15 on 2024-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0008_alter_solicitacaorequisicao_classe_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaorequisicao',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solicitacaotransferencia',
            name='quantidade',
            field=models.FloatField(),
        ),
    ]
