# Generated by Django 4.2.15 on 2024-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_alter_solicitacaorequisicao_entregue_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaorequisicao',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaotransferencia',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
