# Generated by Django 4.2.15 on 2024-10-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_remove_funcionario_cc_funcionario_cc'),
        ('solicitacao', '0009_alter_solicitacaorequisicao_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocadastroitem',
            name='cc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadastro_cc', to='cadastro.cc'),
        ),
    ]
